### ISSUE TITLE
Eco MODE ON AIR & Output: Bad Request

### ISSUE THREAD

**Issue by etehel** [bitfocus/companion-module-smodetech-smodelive#3]
See below: 
![image](https://github.com/bitfocus/companion-module-smodetech-smodelive/assets/40066203/70fed61a-734f-4aae-90aa-124bf332603e)

Appears when triggering Eco MODE, ON AIR and OUTPUT

**Comment by ArthurVasseur** [comment]
Companion is currently using an incorrect `SmodeLive` version (v1.0.1 instead of v1.0.2). ). To rectify this issue, navigate to the `companion-module-smodetech-smodelive` folder perform a git pull. Alternatively, you can clone the repository, and then attempt the operation again. Please remember to set the `Developer modules path` to the parent directory of `companion-module-smodetech-smodelive` folder.

**Comment by etehel** [comment]
fixed on companion v3.2.2
added as required in the smode documentation.
I Close
